### ISSUE TITLE
Tracking: Precipitation data problem

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/plan2adapt-v2#102]
This issue is for tracking in the release milestone only. Actual issue is in climate-explorer-data-prep: https://github.com/pacificclimate/climate-explorer-data-prep/issues/106

**Comment by corviday** [comment]
I think this is resolved, but Arelia said that if we provided her with data in mm/year, she'd do a plausibility check for us.

**Comment by jameshiebert** [comment]
I think that we can safely close this. All indications in our follow-up investigations have shown it to be in good shape.
