### ISSUE TITLE
Tracking: Recompute P2A rules outputs if inputs change

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/plan2adapt-v2#107]
This issue is external to P2A frontend.  https://github.com/pacificclimate/climate-explorer-data-prep/issues/109

**Comment by corviday** [comment]
The impacts server has been updated with a new set of data, incorporating the following improvements:
* double-checked the datasets available in the ensemble (changed ~10 files)
* worked around an issue affecting calculations using data with a winter timestamp (changed ~150 files)
