### ISSUE TITLE
Tracking: Validate that P2A rules engine is executing rules correctly

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/plan2adapt-v2#108]
This issue is external to P2A frontend. https://github.com/pacificclimate/climate-explorer-data-prep/issues/107

**Comment by corviday** [comment]
It seems to be executing rules correctly, but was requesting data incorrectly - queries intended to request the highest winter temperature were instead requesting the highest annual temperature. The impacts server has been updated with improved data.
