### ISSUE TITLE
Optionally disable scroll wheel zooms

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/plan2adapt-v2#144]
From Francis:

> ...there is also an aspect of the way the maps interact with the
>    mouse on my machine that I find frustrating and that seems to be generic
>    to most sites that display maps (e.g., Google maps does the same thing).
>    Specifically, I have an Apple Magic Mouse that has a touch pad on its back
>    instead of a scroll wheel. The map zoom control probably works really well
>    with the scroll wheel, but controlling the map zoom level with the touch
>    pad (you slide a finger up and down to scroll) in a sensible way is
>    virtually impossible (every gesture leads to zooming in or out way too
>    much).

I find this when I'm on a laptop with a touchpad and it's *super* irritating. There are a variety of scroll wheel settings in leaflet. We could either provide a check box to disable the [`scrollwheelzoom`](https://leafletjs.com/reference-1.6.0.html#map-scrollwheelzoom), or possibly tweak the [`wheelDebounceTime`](wheelDebounceTime) to be less sensitive.

**Comment by rod-glover** [comment]
@jameshiebert , I have created controls for all 3 Leaflet scroll settings, and put up a [demo](http://docker-dev01.pcic.uvic.ca:30501/). On my own laptop, I don't experience any untoward behaviour, so perhaps you could provide some feedback on what settings seem to work for you. Then if you are satisfied, we can perhaps ask Francis for some feedback as well.

**Comment by jameshiebert** [comment]
Oddly, I have tried this on four different platforms:

+ Firefox on Desktop Ubuntu w/ scroll mouse
+ Firefox on Laptop Ubuntu w/ touch pad
+ Safari on Mac w/ touch pad
+ Duckduckgo on iOS w/ touch screen

All of theme are completely functional and controllable (which maybe undermines my original reporting of this issue?). *But* I really can't detect any difference in behaviour as I change the settings.

So... either this is a non-issue or it's specific to the Apple Magic Mouse of the original reporter (Francis).

**Comment by corviday** [comment]
I think my non-work computer has an Apple Magic Mouse, I'll give it a shot.

**Comment by corviday** [comment]
I have verified that the map acts _very_ strangely with the Magic Mouse, including somehow getting into a state where the both maps zooms rapidly in and out even when I don't have my hand on the mouse.

**Comment by rod-glover** [comment]
I made a mistake on the scroll-wheel settings: In React Leaflet, only certain properties cause the map to be updated when they are changed. `scrollWheelZoom` is amongst them; the other 2 are not. :(. I will seek a solution to this. Stand by.

**Comment by rod-glover** [comment]
Also, thanks for the feedback about the Magic Mouse. That I do not have in my testing arsenal.

**Comment by corviday** [comment]
[This discussion](https://github.com/Leaflet/Leaflet/issues/4410#issuecomment-340880716) suggests that the Magic Mouse weirdness is due to inertial scrolling. I haven't yet tried disabling inertial scrolling to confirm, but it would make sense with what I observed - events continuing even when my hand isn't on the mouse.

**Comment by corviday** [comment]
I tested it after disabling inertial scrolling in my Mac's accessibility settings, and it works wonderfully.

**Comment by jameshiebert** [comment]
That's excellent to know. But, does that mean there's nothing that we can do in the *code* to make this go away?

**Comment by corviday** [comment]
From one of the leaflet issues you found, someone linked to [lethargy](https://github.com/d4nyll/lethargy), a JS package that can distinguish between deliberate scrolling input by a human and inertial scrolling added after human inputs cease by an operating system. I don't know how difficult it would be to incorporate it, though my suspicion is "fairly", since we aren't doing any direct scroll event handling for the map right now - leaflet does all that. We would be catching and prefiltering it, or something.

**Comment by rod-glover** [comment]
Thanks for the research! `lethargy` looks interesting, and it _may_ be possible to interpose it in the scroll event handling before Leaflet picks it up; that's worth trying. And since I just now dug fairly deeply into Leaflet and React Leaflet, there still may be some options if that simple thing doesn't pan (ha ha) out.

**Comment by rod-glover** [comment]
Here's a [version](http://docker-dev01.pcic.uvic.ca:30501/?wheelDebounceTime=40&wheelPxPerZoomLevel=60) of the demo that actually lets you set the other two scrolling parameters ... via query parameters, which was the only option (apart from the config file, which you can't edit very conveniently). Check the URL, try modifying the params.

I've noticed that values above 40 for `wheelPxPerZoomLevel` don't change anything: zoom of one level per roller click (on my mouse) starts there, and anything larger doesn't make it zoom slower. Smaller values, however, make it zoom faster.

**Comment by rod-glover** [comment]
@corviday , that latest solution you posted looks entirely doable. It is pretty much where my (imprecise) thoughts about it were tending. Very nice to have the necessary code at hand. Thanks!

**Comment by rod-glover** [comment]
I've updated the [demo](http://docker-dev01.pcic.uvic.ca:30501/?wheelDebounceTime=40&wheelPxPerZoomLevel=60) with the lethargy scroll wheel fix. @corviday , could you give it a try and see if it helps?

**Comment by corviday** [comment]
I re-enable intertial scrolling and found it much improved! 

Perhaps 95% of the time I zoomed in or out, it went only a single level (thanks for the convenient zoom level readout!). I did manage to zoom in or out two levels a couple of times, but I think for the most part, with these settings, an Apple Magic Mouse can only zoom in one level at a time.

I did not at any point see the zoom "backtrack" and zoom out a level after zooming in several times, or vice versa.

I did once manage to get it stuck in the flickering-in-and-out mode, but it was much more difficult to do so, only accomplished by flailing around wildly with the mouse.

Generally _much_ less strange and chaotic interactions. The only downside is I think if you _wanted_ to zoom in all the way at once, you would not be able to, and would have to settle for doing it in steps.

**Comment by rod-glover** [comment]
The behaviour of `lethargy` can be fine-tuned using its parameters; I just used the set given in that example. It might be worth setting up a demo with adjustable parameters. What do you think?

**Comment by rod-glover** [comment]
Also, to your final remark: Do you mean that you have to make several strokes on the Magic Mouse to zoom all the way in (or out)? If so, I agree that is an acceptable tradeoff.

**Comment by rod-glover** [comment]
I did set up a demo, and @corviday reports that varying the lethargy parameters does not affect the user experience much. Therefore, I'll add it, parameters set from config, and those set to the recommended values we have.
