### ISSUE TITLE
Docker image is not getting built with REACT_APP_VERSION set

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/plan2adapt-v2#150]
`REACT_APP_VERSION` is blank in the image:

```
[rglover@docker-dev01 ~]$ docker image inspect pcic/plan2adapt-v2-frontend:i137-map-messed-up -f '{{.ContainerConfig.Env}} {{.Config.Env}}'
[PATH=/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin NODE_VERSION=10.20.1 YARN_VERSION=1.22.4 REACT_APP_VERSION=] 
[PATH=/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin NODE_VERSION=10.20.1 YARN_VERSION=1.22.4 REACT_APP_VERSION=]
```

The image must be built with something equivalent to this:

```bash
docker build -t plan2adapt-v2-frontend \
    --build-arg REACT_APP_VERSION="$(./generate-commitish.sh)" .
```

The version *must* be passed as a build-arg; an environment variable external to the build won't do it. I am not sure, but it looks to me as if that is what is happening; the env var is creatd in the GitHub action, but it is not being fed into the build as a build-arg.

**Comment by nikola-rados** [comment]
I can take care of this.  I know we have another image that demands something similar but can't remember which one.  It may be worthwhile ensuring the other image handles it properly.

**Comment by rod-glover** [comment]
The other image is Climate Explorer Frontend. It uses exactly the same mechanism.
