### ISSUE TITLE
Page doesn't load on IE?

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/plan2adapt-v2#184]
There was a report from the BC ACARN webinar this morning that the main P2A page shows up blank when loaded on Internet Explorer. It came from an anonymous person, so I couldn't really follow up. My apologies that no further information is available (i.e. what version?).

**Comment by rod-glover** [comment]
Nope, doesn't work for me either. *Microsoft Edge* runs it, but *IE* fails. Looking into it.

**Comment by rod-glover** [comment]
Question: Are we really going to support a browser that Microsoft itself has deprecated for several years?

**Comment by rod-glover** [comment]
FFS, IE doesn't support *promises*. See [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).

I repeat my question re. support for IE.

**Comment by rod-glover** [comment]
We can polyfill with [promise-polyfill](https://www.npmjs.com/package/promise-polyfill) if we must.

**Comment by jameshiebert** [comment]
I'm happy to not extend support to browsers that MS is not longer supporting, but IE 11 is still supported, right?

That `Promise`s are not supported by IE is... troubling. Let's discuss.

**Comment by rod-glover** [comment]
Possibly my mistake. I thought (wishfully, perhaps) that MS had replaced IE entirely with Edge. But I am probably wrong, since there is evidence of IE 11 all over the internet.

And no, IE 11 is well known not to support native promises. However the polyfill is likely extremely simple to apply. I don't know what implementation it is based on, but at a guess it would be Bluebird, which is an extremely good implementation and probably still in wide use by legacy code.

**Comment by jameshiebert** [comment]
We should probably get this polyfilled if it's relatively easy.

**Comment by jameshiebert** [comment]
![image009](https://user-images.githubusercontent.com/3904316/91592238-14c00380-e913-11ea-9206-f2e0a11293bc.jpg)

**Comment by rod-glover** [comment]
P2A works in Microsoft Edge unmodified.

P2A is broken in Internet Explorer, even _with_ Promise polyfill. The polyfill solves the error reported in this issue, but reveals another, which produces the following error everywhere there should be text. 

```
Error in external text '<key>': SyntaxError: Invalid character.
```

This problem occurs when converting external text values with Markdown. The external text YAML file is received, and parts of it are extracted and passed to components as props (configuration values). The line producing the error message is https://github.com/pacificclimate/plan2adapt-v2/blob/master/src/temporary/external-text.js#L202 and it is in the `catch` for an error in `ReactMarkdown`.

`ReactMarkdown` however produces no such error directly in its own code.

A search for `SyntaxError: Invalid character` doesn't turn up much, but what it does turn up indicates that the error may arise from some kind of character set encoding incompatibility. Tracking down this error will require installing a development environment on a Windows machine with IE installed.

**Comment by rod-glover** [comment]
Superseded by https://github.com/pacificclimate/plan2adapt-v2/issues/209
