### ISSUE TITLE
Responsibility for ncWMS request spikes?

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/plan2adapt-v2#211]
@matthewbenstead reports massive spikes of requets to pcex ncWMS. E.g., at one point we saw > 10,000 hits in under 1 minute. In that instance, it looked like only P2A and ncWMS components were involved, that IP didn't have any PCEX traffic during that time.

[Earlier discussion on Zulip](https://pcic.zulipchat.com/#narrow/stream/183891-CSG-Climate.20Explorer/topic/Load/near/192573316).

**Comment by QSparks** [comment]
Can I close this as stale?

**Comment by corviday** [comment]
I think "the app was acting weird one day four years ago" is probably an issue we can close, yeah.
