### ISSUE TITLE
Support multiple tilecache endpoints?

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/plan2adapt-v2#52]
In PDP we do this: 
```bash
[matthewb@docker-prod01 docker-prod]$ grep TILECACHE_URL fe_deployment.env 
TILECACHE_URL=https://a.tile.pacificclimate.org/tilecache/tilecache.py https://b.tile.pacificclimate.org/tilecache/tilecache.py https://c.tile.pacificclimate.org/tilecache/tilecache.py
```

Investigate to see whether this is feasible to implement in P2A. And whether warranted.

See https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser

**Comment by QSparks** [comment]
The PDP no longer uses this domain-sharding strategy, is it something we still want to look into?

**Comment by rod-glover** [comment]
No.
