### ISSUE TITLE
First beta release: Text content

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/plan2adapt-v2#68]
Review and revise text content in the following:

- [x] Selectors
- [x] Summary tab
- [x] Impacts tab
- [x] Maps tab
- [x] Notes tab
- [x] References tab
- [x] About tab

Note to contributors: Please edit comments below to add your input.

Duplicates: #26

**Comment by rod-glover** [comment]
Selectors: OK

**Comment by rod-glover** [comment]
Summary tab:

- [ ] Move first bottom paragraph to top; adjust wording (above/below).

**Comment by rod-glover** [comment]
Impacts: OK?

**Comment by rod-glover** [comment]
Maps tab:

- [ ] Use smaller text for title, move to bottom

**Comment by rod-glover** [comment]
Notes tab:

- [ ] Revise item 1.
- [ ] Revise item 2.
- [ ] Confirm item 3.

**Comment by rod-glover** [comment]
References tab:

- [ ] Add note that these references will be updated.

**Comment by rod-glover** [comment]
About tab:

- [ ] Remove redundant headings from each sub-tab

**Comment by jameshiebert** [comment]
Link for `climdex.pcic`: https://cran.r-project.org/web/packages/climdex.pcic/index.html

For the `prsn` script, maybe just link to either the [`ce-data-prep` repo](https://github.com/pacificclimate/climate-explorer-data-prep) or the [README entry for generate_prsn](https://github.com/pacificclimate/climate-explorer-data-prep#generate_prsn-generate-snowfall-file).

**Comment by rod-glover** [comment]
The entire text content of the app was revised by Trevor Murdock, and the app was updated in the [Public Release](https://github.com/pacificclimate/plan2adapt-v2/milestone/2) milestone. Therefore this issue is closed.
