### ISSUE TITLE
First beta release: Behaviour

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/plan2adapt-v2#69]
Review and revise the following:

- [x] Dropdown content and behaviour
- [x] Maps behaviour

Note to contributors: Please edit comments below to add your input.

**Comment by rod-glover** [comment]
Dropdowns: OK

**Comment by rod-glover** [comment]
Maps:

- [ ] Coordination

**Comment by jameshiebert** [comment]
This all looks good to me. Closing.
